// <auto-generated />
using System;
using BlackBank.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlackBank.Migrations
{
    [DbContext(typeof(DaneUzytkownikaDbContext))]
    [Migration("20250416154249_DodanoPrzelewy")]
    partial class DodanoPrzelewy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("BlackBank.Models.DaneUzytkownika", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("age")
                        .HasColumnType("INTEGER");

                    b.Property<float>("balance")
                        .HasColumnType("REAL");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("DaneUzytkownikow");
                });

            modelBuilder.Entity("BlackBank.Models.Przelew", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataPrzelewu")
                        .HasColumnType("TEXT");

                    b.Property<float>("Kwota")
                        .HasColumnType("REAL");

                    b.Property<int>("NadawcaID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OdbiorcaID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NadawcaID");

                    b.HasIndex("OdbiorcaID");

                    b.ToTable("Przelewy");
                });

            modelBuilder.Entity("BlackBank.Models.Przelew", b =>
                {
                    b.HasOne("BlackBank.Models.DaneUzytkownika", "Nadawca")
                        .WithMany()
                        .HasForeignKey("NadawcaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlackBank.Models.DaneUzytkownika", "Odbiorca")
                        .WithMany()
                        .HasForeignKey("OdbiorcaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nadawca");

                    b.Navigation("Odbiorca");
                });
#pragma warning restore 612, 618
        }
    }
}
